backend:
  name: git-gateway
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "exhibitions"
    label: "Tentoonstellingen"
    folder: "src/content/exhibitions"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Zaal", name: "room", widget: "string" }
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Beschrijving", name: "description", widget: "text" }
      - { label: "Data", name: "dates", widget: "string" }
      - { label: "Link", name: "link", widget: "string" }

  - name: "news"
    label: "Nieuws"
    folder: "src/content/news"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Datum", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false }
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Beschrijving", name: "description", widget: "text" }